- LICENSE.md
- src/ProtoBuf.jl
- src/codec.jl
- src/gen.jl
- test/services/genproto.sh
- test/services/testsvc.jl
- test/services/testsvc.proto
- test/services/testsvc_pb.jl
codec:
- handle changes in `convert` method in Julia 0.4
- `writeproto` now writes fields with default values if they are explicitly set (causes error with some readers otherwise)
codegen:
- do not generate duplicate `using <package>`
- use relative package path with nested packages
- use 0.4 Dict syntax with `@compat`
> multiple fixes in codec and codegen

- src/codec.jl
- src/gen.jl
- src/gen_descriptor_protos.jl
- test/testcodec.jl
With this change:
- `sfixed32` is serialized as fixed size `Int32`
- `fixed32` as fixed size `UInt32`
- likewise for `sfixed64` and `fixed64`
Prior to this they were getting serialized as `Float32` and `Float64` which was incorrect.
Also code generator generates the `wiretypes` for these specifically since the default `wiretypes` of `Int` and `UInt` are `varints`.
> fix serialization of sfixed and fixed types

- src/ProtoBuf.jl
- src/codec.jl
- test/testcodec.jl
- test/testutilapi.jl
- deprecate add_field and set_field in favor of add_field! and set_field!
- add protobuild method to make creating protobuf types easier
- better copy! method
> protobuild method. deprecate add_field, set_field

- src/ProtoBuf.jl
- src/gen.jl
- src/utils.jl
Since it is possible for ProtoBuf structs not to have some field members filled,
`hash`, `==` and `isequal` should exclude those from the calculation/comparison.
> override hash, isequal, == to consider fill status

- src/codec.jl
- src/gen.jl
- test/compare_ser.jl
- test/runtests.jl
- test/testcodec.jl
- test/testtypevers.jl
- test/testutilapi.jl
- Allow skipping of unknown fields
- Allow serialization across different bits types. Overflow causes the field to get the default value (as if the field is missing)
- Compat changes for 0.4
> allow serialization across similar types

- README.md
- plugin/protoc-gen-julia
- src/gen.jl
- test/proto/module_type_name_collision.proto
- test/testprotoc.sh
This assists in avoid name collisions between packages/modules and messages/types. This is a possible solution for issue #36.
> fix #36: Adds '_pb' Postfix to all Module Names

- README.md
- src/gen.jl
- src/utils.jl
This changes constructors of generated types to optionally accept keyword arguments specifying field values.
With no keyword arguments, this behaves the same as the earlier generated empty constructor.
When keyword arguments are supplied, this behaves like the `protobuild` utility method.
e.g.:
````
julia> include("A.jl")
A
julia> using A
julia> d = Description()
A.Description(#undef,#undef,0.0)
julia> d = Description(;id="myid", name="myname", date=time())
A.Description("myid","myname",1.450808600240597e9)
````
This is similar but slightly more conventient than using `protobuild`:
````
julia> d = protobuild(Description, Dict(:id=>"myid", :name=>"myname", :date=>time()))
A.Description("myid","myname",1.450808707560326e9)
````
The `protobuild` method can be deprecated in a future update. …
> generate non empty constructors

- src/gen.jl
Generated code can not redefine `Type` in Julia code.
If the specification contains an entity named `Type`, it will be generated as `_Type`.
> add `Type` to reserved keywords

- src/gen.jl
- test/proto/a.proto
- test/proto/b.proto
For an enum's default value we are currently using the "long" type name, this causes the .jl file to set the default using the a path to the value which isn't valid based on the modules that were imported.  
In the example below the default is set to `Base.A.Selection.z`.  However, since just the modules `A` is brought in with the `using` keyword if we use the "short" type name here we'll appropriately reference the enum default as `Selection.z`.
Note: this only happens with the nested package names like the example below is using (ie: `Base.A` and `Base.B`).
> Enum bugfix

- README.md
- src/ProtoBuf.jl
- src/utils.jl
- test/testcodec.jl
Makes it easier to show enum values.
e.g. for an enum named `TestEnum` with a value `ENUMVAL1`
````
julia> v = TestEnum.ENUMVAL1;
julia> enumstr(TestEnum, v) == "ENUMVAL1"
true
julia> println(enumstr(TestEnum, v)
ENUMVAL1
````
> enumstr: utility method get name for enum value

- README.md
AFAICT from https://github.com/tanmaykm/ProtoBuf.jl/blob/master/src/codec.jl
The mapping of float is too and from Float32.
(rather than Float64) as indicated in the readme
> float = Float32

- .travis.yml
- PROTOC.md
- README.md
- plugin/protoc-gen-julia
- src/ProtoBuf.jl
- src/gen.jl
- test/testwellknown.jl
This makes code generated for Google's well-known type extensions a sub-module of ProtoBuf.
Julia protoc now treats them specially and imports the ProtoBuf supplied sub-module when encountered.
Also remove Julia 0.3 support, update CI and coverage.
Fixes #77
> make google wellknown types a submodule (fix #77)

- src/codec.jl
- test/testcodec.jl
- test/testtypevers.jl
fixes #86
Strangely, it looks like both negative `int32` and `int64` should encode to 10 bytes.
from https://developers.google.com/protocol-buffers/docs/encoding:
> if you use int32 or int64 as the type for a negative number, the resulting varint is always ten bytes long – it is, effectively, treated like a very large unsigned integer.
This alters int32 varint
- reading to accept both 10 and 5 byte serialization formats (like the C implementation and unlike python)
- writing to always serialize 10 bytes
> fix negative int32 varint format

- REQUIRE
Compat.jl v0.17.0 needed for `@compat abstract type`
> correct compat version

- src/codec.jl
When reading ~3.3 million ProtoBuf delimited records from a file, the original performance was:
420.184926 seconds (685.35 M allocations: 25.293 GiB, 1.77% gc time)
After fixing the BitArray dimension specification, the time reduced to:
88.419822 seconds (466.65 M allocations: 20.081 GiB, 7.25% gc time)
> Improved performance by fixing number of dimensions of BitArray

- src/codec.jl
- src/gen.jl
- test/proto/recursive.proto
- test/testprotoc.sh
Julia does not allow mutually-circular type declarations yet (https://github.com/JuliaLang/julia/issues/269).
This change overcomes that by using `Any` to break cycles, while keeping the actual type information separately as metadata to be used while re-constructing objects from serialized data.
> generate code for mutually-circular message defns

- src/ProtoBuf.jl
- src/codec.jl
- src/gen.jl
- src/google/any_pb.jl
- src/google/api_pb.jl
- src/google/descriptor_pb.jl
- src/google/duration_pb.jl
- src/google/empty_pb.jl
- src/google/field_mask_pb.jl
- src/google/plugin_pb.jl
- src/google/source_context_pb.jl
- src/google/struct_pb.jl
- src/google/timestamp_pb.jl
- src/google/type_pb.jl
- src/google/wrappers_pb.jl
- src/utils.jl
- test/testcodec.jl
to avoid clashing `copy!` methods (and other such generic names) with other packages
> protobuf generated types extend abstract ProtoType

- src/gen.jl
In the generated code, use fully qualified names for field types instead of short name.
The motivation was stated in https://github.com/JuliaIO/ProtoBuf.jl/issues/97
I have been using a patched version for a few months, tested extended in a few ProtoBuf heavy projects (mostly as GRPC message types in a micro-service environment).
Within the pull request are a few changes,
1. `short_type_name` is renamed to `field_type_name` to better reflect its purpose as well as the new implementation
2. Instead of finding the shortest name it instead generate the fully qualified name. That is it returns `full_type_name` in most cases by `ProtoBuf.$full_type_name` when it is Google protobuf type.
3. In generated code, instead of `using $dependency`, now only `import $dependency`. And relies on the above …
> using fully qualified names

- gen/google/protobuf/any.proto
- gen/google/protobuf/api.proto
- gen/google/protobuf/compiler/plugin.proto
- gen/google/protobuf/descriptor.proto
- gen/google/protobuf/duration.proto
- gen/google/protobuf/empty.proto
- gen/google/protobuf/field_mask.proto
- gen/google/protobuf/source_context.proto
- gen/google/protobuf/struct.proto
- gen/google/protobuf/timestamp.proto
- gen/google/protobuf/type.proto
- gen/google/protobuf/wrappers.proto
- src/codec.jl
- src/gen.jl
- src/google/any_pb.jl
- src/google/api_pb.jl
- src/google/descriptor_pb.jl
- src/google/duration_pb.jl
- src/google/empty_pb.jl
- src/google/field_mask_pb.jl
- src/google/plugin_pb.jl
- src/google/source_context_pb.jl
- src/google/struct_pb.jl
- src/google/timestamp_pb.jl
- src/google/type_pb.jl
- src/google/wrappers_pb.jl
- use latest proto files for wellknown protos
- fix a codegen issue when a may type field has a defered type
- regenerate julia code with latest ProtoBuf.jl
- now that it can handle cyclic type references, we do not need to manually update protos or generated code
>  regenerate wellknown protos (with new compiler)

- REQUIRE
- src/gen.jl
- test/setup_protoc3.sh
Minor updates:
- use `split` from Compat.jl
- update protoc3 install scripts to install binaries when possible, reducing setup time, and making CI (travis) faster
> use split from Compat

- .travis.yml
- PROTOC.md
- Project.toml
- plugin/protoc-gen-julia
- src/utils.jl
- test/testprotoc.jl
- test/testprotoc.sh
This makes two changes:
1. Have the script `Pkg.activate` its parent directory (which now
contains an appropriate Project.toml to make that work). This
is necessary for things to work if `ProtoBuf` is not installed
in the top level environment (e.g. it is cloned or a dependency
in a custom environment).
2. Adds the `ProtoBuf.protoc` command that returns a `Cmd` object
which is appropriately set up to use the plugin (setting up
the correct julia version and plugin path).
cc @tanmaykm for review
cc @StefanKarpinski @KristofferC for input on whether there's something better to do with respect to environments here (e.g. for `ProtoBuf.protoc` do we instead somehow want to pass through the environment of the current julia process).
> Improve ProtoBuf generation on 1.0

- USAGE.md
- src/utils.jl
- test/services/testsvc.jl
- test/services/testsvc_pb.jl
- test/testcodec.jl
- test/testutilapi.jl
Now that ProtoBuf.jl depends on 1.0, we can just use regular
setproperty! syntax (a.b = c) rather than having to use set_field!.
> Use setproperty! rather than set_field!

- .travis.yml
- Project.toml
- README.md
- REQUIRE
- USAGE.md
One of the examples in USAGE.md did not mark struct to be a `ProtoType`. fixes #126
Also update Project.toml and travis configuration.
> correct example in USAGE.md

- src/gen.jl
- test/proto/inf_nan.proto
- test/testprotoc.sh
Previously these would appear unchanged in the Julia code (e.g., as
"inf" and "nan" literally) and therefore the resulting code would not
compile.
Ref https://developers.google.com/protocol-buffers/docs/reference/proto2-spec#floating-point-literals
> Fix parsing of infinity and NaN default values

- plugin/protoc-gen-julia
Recent Pkg prints extra error messages to stdout when activating
an environment which corrupts the output. Instead, use `--project`,
since we now support only julia >= 1.
> Fix protoc plugin with recent Pkg

- src/ProtoBuf.jl
ProtoEnum is not defined any more. It was still exported because of an oversight in #141. This fixes it.
Fixes #142
> do not export ProtoEnum anymore

- Project.toml
- src/ProtoBuf.jl
ProtoBuf uses Base.hasproperty, however this was introduced in Julia 1.2.
This adds `hasproperty` for Julia versions < 1.2.
Also bumped version to v0.9.1 in preparation for tagging.
fixes #147
> add hasproperty for Julia < 1.2 compat

- src/codec.jl
- src/gen.jl
- src/google/any_pb.jl
- src/google/api_pb.jl
- src/google/descriptor_pb.jl
- src/google/duration_pb.jl
- src/google/empty_pb.jl
- src/google/field_mask_pb.jl
- src/google/plugin_pb.jl
- src/google/source_context_pb.jl
- src/google/struct_pb.jl
- src/google/timestamp_pb.jl
- src/google/type_pb.jl
- src/google/wrappers_pb.jl
- test/services/testsvc.jl
- test/services/testsvc_pb.jl
- test/testcodec.jl
- test/testtypevers.jl
- test/testutilapi.jl
We need to keep track of whether a field value has been set from the message or because of the default value rule. This is required to be able to generate code for structs having `oneof` fields among other fields.
fixes: #146
> track default values, fix oneof code generation

- src/svc.jl
We are directly fetching a symbol from module and `getfield` is more efficient than `eval` for this purpose as pointed out in #156.
fixes #156
> use getfield instead of eval to get service method

- PROTOC.md
This PR fixes some old code in PROTOC.md that is broken as of `v0.11`. `protoc` calls `run` on its own now, so it's return value should not be passed to `run` in these examples.
> Fix PROTOC.md

- src/gen.jl
- Fix service code gen for nested package/modules. Use relative qualifiers for service input and output parameter types when generating services in packages/modules that are nested.
- Julia protoc code generator used to look at service code generation options of other languages to switch that feature on.
Which is not necessary and this will remove that restriction. We will not depend on other languages service generation flags any more.
> service code generation improvements

- src/gen.jl
- test/proto/t2.proto
Nested structs are allowed in proto definition. In Julia nested structs are generated as separate structs with names flattened out using `_` as separator.
E.g. with a proto file definition:
```
...
message MA {
required string a = 1;
optional MB b = 2;
message MB {
optional MC c = 1;
}
}
...
service TestServicePkgP {
rpc Method1(MA.MB) returns(MC);
}
```
The service method `Method1` generated will have the input type `MA_MB`.
```
mutable struct MA_MB <: ProtoType
...
end
...
Method1(stub::TestServicePkgPBlockingStub, controller::ProtoRpcController, inp::MA_MB)
```
That was incorrectly generated as `MA.MB` earlier, which this PR fixes.
fixes #167
> correct codegen for nested protobuf structs

- src/gen.jl
This feature would allow me to create protobuf objects more easily. Rather than constructing the object in different ways, I can pass a field value that is possibly unavailable and the code just ignores it. For example, from plugin.proto:
```julia
CodeGeneratorResponse(; error)
```
Currently, I would have to write something like:
```julia
if error === nothing
CodeGeneratorResponse()
else
CodeGeneratorResponse(; error)
end
```
Or I would have to write:
```julia
r = CodeGeneratorResponse()
if error !== nothing
r.error = r
end
```
The issue is that the code becomes clumsy very quickly when 
1. I have to deal with more fields like that 
2. I have to work this way for nested structs
> Ignore nothing when setting a field

- src/codec.jl
- test/testcodec.jl
This is consistent with the existing handling of empty `Vector`s.
Added tests to demonstrate both the old and new behavior.
> fix: readproto returns empty `Dict` property

- src/gen.jl
`Set` can end up being used as a name by schemas, which then causes the generated code to error out when loaded. This change adds `Set` as a known keyword to be mangled into `_Set` to avoid this issue, similarly to how other types in Base are handled.
> Add Set as a keyword

- src/codec.jl
This PR removes the need for the `WIRETYPES` lookup table by specializing the lookup based on Julia types instead.
The lookup table is replace by `wire_type`, `_read_value` and `_write_value` functions.
This has a significant performance improvement for writing, but does not seem affect reading.
For example:
```jl
julia> using ProtoBuf, BenchmarkTools
julia> using ProtoBuf.google.protobuf
julia> dv = DoubleValue(value=64.0)
julia> dvmeta = ProtoBuf.meta(typeof(dv))
julia> @benchmark writeproto(iob, dv, dvmeta) setup = (iob = PipeBuffer();)
BenchmarkTools.Trial: 10000 samples with 308 evaluations.
Range (min … max):  279.825 ns …  14.253 μs  ┊ GC (min … max): 0.00% … 97.90%
Time  (median):     283.951 ns               ┊ GC (median):    0.00%
Time  (mean ± σ):   297.450 ns ± 188.815 ns  ┊ …
```
> Make wiretypes into julia types and specialize methods on these types

- src/codec.jl
- test/testcodec.jl
This PR addresses #191.
- The`FixedSizeNumber` or `SignedNumber` are now handled correctly in both `readproto` and writeproto` by converting based on `attrib.ptyp`. 
- To keep the speedup of #188, I converted `attrib.ptyp` to the corresponding Julia type.
- I added tests for a known value of concrete types (`Int64`,  `SignedNumber{Int64}`...) and arrays of concrete types.
A minor fix of conversions of `FixedSizeNumber` and `SignedNumber` is also in this PR.
Note that the meta for dictionaries seem not to support `FixedSizeNumber` or  `SignedNumber`
https://github.com/JuliaIO/ProtoBuf.jl/blob/0428aeeda98ce86d6528bc28403d5d2bad5b9e15/src/codec.jl#L571
due to `mapentry_meta` being called with the julia type as argument, and only use that to set `ProtoMetaAttribs`, an issue that predates the …
> fix incorrect serialization of some concrete types

- src/codec/decode.jl
- test/test_decode.jl
Until now, when we encountered an unknown enum member, we pretended that we got the default value. This is not very useful and could lead to a lot of confusion. This is what the [spec](https://developers.google.com/protocol-buffers/docs/proto3#enum) has to say about this:
*During deserialization, unrecognized enum values will be preserved in the message, though how this is represented when the message is deserialized is language-dependent. In languages that support open enum types with values outside the range of specified symbols, such as C++ and Go, the unknown enum value is simply stored as its underlying integer representation. In languages with closed enum types such as Java, a case in the enum is used to represent an unrecognized value, and the underlying integer can be accessed …
> Allow storing unknown enum values

- src/parsing/proto_types.jl
- test/test_parser.jl
This change allows fields in messages to have hex field numbers. Previously a message of the following form would have raised an error:
```proto2
message A {
required uint32 b = 0x1234;
}
```
Added unit tests to test parsing of both decimal and hex field numbers. 
Question for maintainer: Are there other places where I can propagate this in a followup?
> Message fields can have hex field numbers

- src/parsing/proto_types.jl
- test/test_parser.jl
Fixes https://github.com/JuliaIO/ProtoBuf.jl/issues/211#issuecomment-1241219281
> Allow trailing semicolon after `oneof` fields

- Project.toml
- src/codegen/names.jl
- src/codegen/toplevel_definitions.jl
- test/test_codegen.jl
This PR includes a few small fixes;
- I have added the reserved names `Array`, `Vector`, `Dict`, `Union` and `OneOf`.  These are names which, if used, would break the generated code because their `Base` names are used without any accommodation to qualify the names in those cases.  Ideally I'd like to add a whole lot more (every exported type from `Base`) as they can lead to nasty surprises even if they don't technically break the generated code, but technically adding any other reserved words would be breaking, whereas this PR is not.
- I fixed an edge case in which a space would be omitted when generating code for a 0-field `struct` which inherits from `AbstractProtoBufMessage`.  This would lead to broken code such as `struct A <: AbstractProtoBufMessageend`.  I have added a unit test …
> a few small fixes for codegen

- src/codegen/encode_methods.jl
This changes codegen for `encode` and `_encode_size` methods for OneOf types. This should help type inference, definitely in the case when we don't parameterize the parent struct. E.g. this changes code generated in tests for "complex_message_pb.jl" from:
```julia
...
if isnothing(x.oneof_field);
elseif x.oneof_field.name === :oneof_bytes_field
PB.encode(e, 17, x.oneof_field[])
elseif x.oneof_field.name === :oneof_string_field
PB.encode(e, 18, x.oneof_field[])
elseif x.oneof_field.name === :oneof_uint32_field
PB.encode(e, 19, x.oneof_field[])
elseif x.oneof_field.name === :oneof_uint64_field
PB.encode(e, 20, x.oneof_field[])
elseif x.oneof_field.name === :oneof_int32_field
PB.encode(e, 21, x.oneof_field[])
...
```
to
```julia
...
if isnothing(x.oneof_field);
elseif x.oneof_field.name === …
```
> Add type assertions when encoding OneOf members

- test/test_lexers.jl
Found as part of testing for JuliaLang/julia#46372 - JuliaSyntax.jl rejects `\777` as this is above the maximum octal value for a `UInt8`.
The reference parser incorrectly saturates such invalid char literals to `\xff` and you've already got a test for that.
> Remove invalid escape sequence

- Project.toml
* Update compat for `TranscodingStreams` to include v0.10.
* Include compats for stdlibs `Dates`, `Test`, `TOML`.  Ref https://discourse.julialang.org/t/psa-compat-requirements-in-the-general-registry-are-changing/104958
* Include compats for `Aqua` and `JET`, to pass tests that use `Aqua` and `JET`.
> compat updates

- Project.toml
- src/codegen/encode_methods.jl
- test/test_codegen.jl
- test/test_protojl.jl
- test/test_protos/complex_message.proto
Currently, when we're encoding a value to send we check something like `x != zero(T)` to decide if we're going to send anything. This is fine for almost every type, but for floats in particular `==` and `isequal` are not the same. In particular, `0.0 == -0.0`, which means that `-0.0` has no message sent and roundtrips back to `0.0`, which is incorrect. This is called out directly in the proto spec https://protobuf.dev/programming-guides/proto3/, as "-0 is considered distinct and will be serialized."
The fix is for float types we should instead use `isequal`.
> Fix a bug with sending -0.0 for floats

- src/codegen/decode_methods.jl
Noticed when running ExplicitImports.jl on a module with PB generated files. 
Got:
```jl
Module `Foo.Rel` has qualified accesses to names via modules other than their owner as determined via `Base.which`:
- `skip` has owner `Base` but it was accessed from `ProtoBuf` at `~/Foo/src/Rel/Rel_pb.jl:1019:16`
```
> Access `skip` from its owning module
